### ISSUE TITLE
Compatability with liquibase 3.7.0+

### ISSUE THREAD

**Issue by mjad-dazn** [CDKGlobal/liquibase-snowflake#4]
Hi, this extension is currently API incompatible with liquibase 3.7 what would it take to upgrade and is there any work planned here for this? 
Thanks
Matt

**Comment by bruce-szalwinski** [comment]
Sorry for the slow response.  I'll make this available over on my fork and see if CDK will accept the change.  Not sure if anyone at CDK is watching this repo.

**Comment by bruce-szalwinski** [comment]
I forked this project and upgraded to latest liquibase release, 3.8.5.  See https://github.com/bruce-szalwinski/liquibase-snowflake for the latest code.  Also see https://liquibase.jira.com/wiki/spaces/CONTRIB/pages/113372651/Snowflake+extension.  Sample app that uses this version is available at https://github.com/bruce-szalwinski/liquibase-snowflake-sample.

**Comment by mjad-dazn** [comment]
@bruce-szalwinski brilliant, thanks very much for this update
